version: '3.9'
services:
  db:
    image: mysql:8.0.26
    environment:
      - MYSQL_DATABASE=pfa_docker
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/dbdata:/var/lib/mysql
    networks:
      - pfa-db-backend

  backend:
    build: ./backend
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    networks:
      - pfa-db-backend
      - pfa-nginx-backend
    depends_on:
      - db

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 8000:80
    networks:
      - pfa-nginx-backend
    depends_on:
      - backend

networks:
  pfa-db-backend:
    driver: bridge
  pfa-nginx-backend:
    driver: bridge